stages:
  - build
  - unit_test
  - docker_build_and_push
  - deploy

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  DOCKER_DRIVER: overlay2

cache:
  paths:
    - .m2/repository

build:
  stage: build
  image: maven:3.9.6-eclipse-temurin-17
  tags:
    - maven-runner
  script:
    - mvn $MAVEN_CLI_OPTS clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 hour

unit_test:
  stage: unit_test
  image: maven:3.9.6-eclipse-temurin-17
  tags:
    - maven-runner
  script:
    - mvn $MAVEN_CLI_OPTS test
  artifacts:
    reports:
      junit: target/surefire-reports/TEST-*.xml

docker_build_and_push:
  stage: docker_build_and_push
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  tags:
    - docker-runner
  dependencies:
    - build
  script:
    - cp target/*.jar app.jar
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD" $DOCKER_REGISTRY
    - docker build -t $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker tag $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA $DOCKER_IMAGE:latest
    - docker push $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $DOCKER_IMAGE:latest
  artifacts:
    paths:
      - Dockerfile

deploy:
  stage: deploy
  image: alpine:3.18
  tags:
    - deploy-runner
  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $DEPLOY_SSH_HOST >> ~/.ssh/known_hosts
  script:
    - ssh $DEPLOY_SSH_USER@$DEPLOY_SSH_HOST "docker login -u $DOCKER_USER -p $DOCKER_PASSWORD $DOCKER_REGISTRY"
    - ssh $DEPLOY_SSH_USER@$DEPLOY_SSH_HOST "docker pull $DOCKER_IMAGE:latest"
    - ssh $DEPLOY_SSH_USER@$DEPLOY_SSH_HOST "docker stop reviewsystem || true && docker rm reviewsystem || true"
    - ssh $DEPLOY_SSH_USER@$DEPLOY_SSH_HOST "docker run -d --name reviewsystem -p 8089:8089 --env-file /path/to/your/envfile $DOCKER_IMAGE:latest"
  only:
    - main
