spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reviewsystem?useSSL=false&serverTimezone=UTC
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    allowPublicKeyRetrieval: true
    useSSL: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
  file:
    name: logs/reviewsystem.log

server:
  port: 8089

jlimport:
  source-aws: true # set to true to use AWS S3, false for local folder
  required-fields:
    top-level:
      - hotelId
      - hotelName
      - comment
    comment:
      - hotelReviewId
      - providerId
      - rating
      - reviewComments
      - reviewDate
      - reviewerInfo
  s3:
    bucket: *****
    region: *****
    access-key: ******
    secret-key: *****
    prefix: files
  batch-size: 25
  schedule-enabled: true
  schedule-cron: "0 0/5 * * * ?" # every 5 minutes
  folder-path: *****
  temp-dir: *****
